### ISSUE TITLE
Actualizar código a versión 2.12

### ISSUE THREAD

**Issue by Juanmcuello** [pablitoh/DiarioLibre#1]
@pablitoh , veo que en el [sitio de la extensión](https://chrome.google.com/webstore/detail/diario-libre/fcgpobbjbjimefiffeofcimhmibiikco) está publicada la versión 2.12, pero acá en repo está la 1.5. ¿se podrá actualizar el repo con el código de la última versión?

**Comment by pablitoh** [comment]
Sisi seguro ! En el transcurso del dia lo hago !

**Comment by pablitoh** [comment]
Perdon por la demora, ya está hecho el cambio ! Saludos ! y Gracias por el interes!

**Comment by Juanmcuello** [comment]
:+1:
